In [2]:
import torch
from dgl.data.citation_graph import CoraGraphDataset, CiteseerGraphDataset, PubmedGraphDataset


In [5]:
train_cls_mask = torch.zeros(10, dtype=bool)

In [6]:
train_cls_mask

tensor([False, False, False, False, False, False, False, False, False, False])

In [2]:
import torch
a = torch.randint(10, size=(3,2,5))

In [3]:
torch.randperm(10)

tensor([1, 0, 5, 2, 4, 9, 3, 6, 7, 8])

torch.Size([3, 5])

In [7]:
torch.cat(torch.unbind(a, dim=1), dim=0).shape

torch.Size([6, 5])

In [8]:
mask = torch.randint(10, (6,6))
mask

tensor([[8, 5, 4, 8, 4, 6],
        [4, 1, 1, 8, 8, 8],
        [9, 7, 0, 5, 2, 1],
        [6, 3, 4, 5, 9, 0],
        [5, 2, 1, 2, 5, 5],
        [2, 4, 0, 7, 0, 6]])

In [9]:
logits_mask   = torch.scatter(torch.ones_like(mask),   # 2Nx2N的全一矩阵 target 张量中填充0 
                                      1,  # 按行 表示(2N, 2N)矩阵的
                                      torch.arange(2 * 2).view(-1, 1),  # index，[0,1,2,... 32x2-1] 
                                      0)

In [10]:
logits_mask

tensor([[0, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 1],
        [1, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [11]:
torch.arange(2 * 2).view(-1, 1)

tensor([[0],
        [1],
        [2],
        [3]])

In [12]:
logits_mask

tensor([[0, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 1],
        [1, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [15]:
logits_mask.sum(1, keepdim=True)

tensor([[5],
        [5],
        [5],
        [5],
        [6],
        [6]])

In [ ]:
for i in range(100):
    print(i)
    continue
    print("abc")